In [1]:
#1.Debug the given code
import pandas as pd
 
data = {'Feature1': ['10', '20', 'Thirty'], 
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1']= pd.to_numeric(df['Feature1'], errors='coerce') #errors='coerce' 
#means any value that can't be converted (like 'Thirty') will be replaced with NaN.

print(df)

#Ans: 'Thirty' is not a valid number so change it as int pd.to_numeric


   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [2]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace=True)  # Error: fillna() does not modify in place, so add inplace=True 

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [3]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([1, 2, 3, 4, 5])  # Error: Expected 2D array, got 1D array instead, 
Xreshape=X.reshape(-1,1)       #when we train model python excepts 2d arra which means both row and column 
y = np.array([2, 4, 6, 8, 10])


model = LinearRegression()
model.fit(Xreshape, y)
print(model.predict([[6]]))  # Predict for new value

print(Xreshape)


[12.]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D
data_reshape=data.reshape(-1, 1) #or we can convert np.array([[10], [20], [30], [40], [50]]) too
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data_reshape)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [5]:
#5.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric
le = LabelEncoder()
y_encoded = le.fit_transform(y)

model = LogisticRegression()
model.fit(X, y_encoded)

print(model.predict([[4, 5]]))
print(y_encoded)


[1]
[1 0 1]


In [6]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
X= df[['Category']]

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(X)  
print(encoded)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [7]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
#y = [0, 1, 0] #target variable has only 3 values expected 4 so it makes inconsistent numbers of samples
y = [0, 1, 0, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train:", X_train)
print("y_train:", y_train)



X_train: [[1, 2], [5, 6], [7, 8]]
y_train: [0, 0, 1]


In [12]:
#7.from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

le = LabelEncoder()
y_encoded = le.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train,y_encoded)

print(model.predict([[3, 4]]))
print(y_encoded)


[1]
[1 0 1]


In [13]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer # one of the pre processing method 

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train_imputed, y_train)  

prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)



Predicted Output: [20.]


In [14]:
#9.
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

le= LabelEncoder()
y_train_labeld=le.fit_transform(y_train) 

model = DecisionTreeClassifier()
model.fit(X_train, y_train_labeld)

print(y_train_labeld)
print(model.predict([[6,8]]))


[1 0 1]
[1]


In [15]:
#10.
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)


model = SVC()
model.fit(X_train_scaled, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


[0]
